const Tips = [
  "Get ready to click!",
  "If you read this, you're gay. And I'm proud of you.",
  "If you read this, you're not gay. How subversive!",
  "TIP: If you click Kevster's belly enough times, he'll fart.",
  "ALL HAIL THE GOD EMPEROR!",
  "Did you know? There is an underground resistance movement planning to overthrow Kevster.",
  "Have we gone too far?",
  "Do you think God stays in heaven because he, too, lives in fear of what he's created?",
  "Hi! Bye!",
  "Check out threesan.github.io!",
  "Check out hivebackpack.com!",
  "Did you know? This game was made by space apes from Jupiter.",
  "Happy Pride Month to David Fiddes!",
  "ow i was trying to write a caption and i bit my tognue owowowow",
  "^w^",
  "TIP: Click the reset button 10 times for 10,000,000 KevBucks.",
  "For support, email snookerinc51@gmail.com!",
  "TIP: Click the 'Back to Home' button to find a really cool secret webpage!",
  "TIP: Hover over buttons in the Navbar to see what they do.",
  "Did you know? There are over 4 upgrades in this game!",
  "Stop playing. I don't think you're good enough at games to play this. Close the window now.",
  "Baba Booey",
  "FLETCHER NATION 2024",
  "KEVSTER NATION 2024",
  "Rishabh was here!",
  "TIP: Look behind you.",
  "TIP: Looking in your bathroom mirror and saying 'Kevster' 3 times will unlock the final upgrade.",
  "Did you know? All of the original creators of Kevster Clicker are now in jail!",
  "Shout outs to Devansh 🔥",
  "hi",
  "Did you know? This loading screen isn't actually loading anything. We just wanted to waste your time.",
  "Did you know? This game was made by Mongolian CSS Monks.",
  "Did you know? Project MKUltra was an illegal human experiments program designed and undertaken by the U.S. Central Intelligence Agency (CIA) to develop procedures and identify drugs that could be used during interrogations to weaken people and force confessions through brainwashing and psychological torture. It began in 1953 and was halted in 1973. MKUltra used numerous methods to manipulate its subjects' mental states and brain functions, such as the covert administration of high doses of psychoactive drugs (especially LSD) and other chemicals without the subjects' consent, electroshocks, hypnosis, sensory deprivation, isolation, verbal and sexual abuse, and other forms of torture.",
  "TIP: Click the 'How to Play' button to learn how to play the game.",
  "TIP: Click the 'Credits' button to see the credits.",
  "TIP: Click the big round button to get KevBucks.",
  "TIP: Click the 'Reset' button to reset the game.",
  "TIP: The God Emperor is always watching. Don't disappoint him.",
  "What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little 'clever' comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.",
  "Chair launch?",
  "Welcome to Kevster Clicker!",
  "182.176.10.27 Nice IP, kiddo.",
  "50.44334, -4.956026",
  "TIP: Click a locked upgrade 1000 times to instantly unlock it!",
  "Sorry nothing",
  "TIP: Don't drink water from the tap tonight.",
  "Did you know? Every 5 levels, the background changes!",
  "TIP: Press SPACE to enter Kookie Mode!",
  "Did you know? This game only took 5 minutes to make!",
  "Did you know? This game had a budget of $10,000,000!",
  "I'm severely in debt. Please contact my PayPal at 'patrick.scotts@gmail.com'. Please",
  "Did you know? In the game's files, there's a hyperrealistic 3D model of Kevster.",
  "Did you know? The game's soundtrack is available on Spotify!",
  "Did you know? There are explicit images hidden somewhere on this website. Try and find them!",
  "Did you know? The FBI is after me",
  "Kevster Clicker is a 2024 web-based browser clicker game developed by Snooker Inc, a subsidiary of Burgerbross S.p z.o.o in HTML5 and CSS3. The game was developed in only a week while the dev team drank milk and ate oat cookies all day long. The game was directed by elusive auteur Rishabh Sandhu, who commanded the submissive yet talented developer David Fiddles to develop the game for him while he merely laid out the assets and designed some kick-ass music. Since Rishabh only had his brain implanted 2 years prior at the age of 15 by the Mind Monks of Tanzania, he couldn't think up any of the game's concepts by himself at all. It was impossible. So, he manipulated and gaslit talented mind user Leon Carpin into conceptualising various upgrades, trinkets and doodads for him to use. Famously, he paid Leon Carpin a Half Penny and 2 Farthings in the Lord's Currency. The team hired two goblins from a deep chasm known as Daniels and Harry to design assets and playtest the game, which they obliged to, so long as the devteam consistently supplied them with the bones of a chicken every new moon. In what is now pop culture history, the game's development abruptly ended when the development team was found universally guilty of intergalactic fraud on 6302 counts after failing to repay loans to the Coalition of Mars, which they had taken out to fund the game's development. The team are now serving individual sentences of 1300 years in a quantum jail in Pennsylvania. The game released on August 12, 2026.",
  "Good Morning!",
  "Good Night!",
  "This game contains 500 unlicensed pictures of Mario. Nintendo can't stop me",
  "Did you know? The game's 'Main Theme' took 500 years to make, and was composed by Renaissance bards! Many died in the process.",
  "TIP: You can click the button",
  "Did you know? This game contains over 7 realms!",
  "Kevster want boing boing!",
  "Nah, I'd win.",
  "Did you know? Kevster alone is the Honored One.",
  "Jika anda menterjemah ini, anda adalah bodoh. Hidup Malaysia",
  "Donate to Kevster's BBL fund today!",
  "Snooker on top!",
  "Fun fact: Kevster isn't even a real person.",
  "Look up 'baby alien bus'",
  "Mop bucket?",
  "Close the game, Kevster's coming.",
  "Did you know? Kevster plays snooker, but the game contains pool cues. This is because the devs are Fucking stupid",
  "Pay $9.99 to unlock the full game.",
  "Buy the Kevster Deluxe upgrade for $12.99/year!",
  "Did you know? You can buy KevCoins for only $1.99!",
  "Did you know? This website is actually a virus! Don't believe me? Check Windows Defender.",
  "You know when you breathe manually?",
  "Breathe in. Now you're breathing manually.",
  "You blinked.",
  "You ever start blinking manually?",
  "Did you know? To get rid of hiccups, take a deep breath and hold the breath & your nose for 10 seconds while puffing out your cheeks.",
  "Did you know? We legally own the rights to your brain.",
  "Did you know? Kevster uses a Tree Modus and fights with a Mopkind specibus.",
  "Chair launch, anyone?",
  "Did you know? We lost the clones of Kevster. We don't know where they are.",
  "Did you know? Kevster is actually a clone of the original, who went AWOL 12 years ago.",
  "TIP: Stop playing",
  "Better than Fortnite!",
  "Better than Ocarina of Time!",
  "Better than Grand Theft Auto V!",
  "Better than Super Mario Galaxy!",
  "Better than The Thousand Year Door!",
  "Better than Breath of the Wild!",
  "Better than Minecraft!",
  "Check out Button Bot!",
  "Shout outs to Snooker Legends!",
  "R.I.P. SNOOKER ON TOP",
  "Fun fact: Kevster is currently 100m away. Hide - you can't run.",
  "LONG LIVE THE GOD EMPEROR!",
  "Did you know? Kevster is actually just a man named Frank.",
  "Fun fact: Kevster once killed 10 men with a pencil.",
  "Game of the Year 2024!",]
export default Tips

